### ISSUE TITLE
*CLINICAL CONDITION* Influenza Like Illness (ILI)

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/ics-research#21] opened 2020-04-22 11:22 UTC

**Comment by brianmackenna** [comment] 2020-08-24 11:41
Sorry to reopen this but a couple of things

1: The methodology needs documenting at https://codelists.opensafely.org/codelist/opensafely/influenza-like-illness/2020-05-18/
2: Appropriateness of name: This may be fixed with the methodology but when using in the [flu dashboard](https://github.com/opensafely/flu-vacc-research/tree/master/notebooks) two people have queried that this codelist is not what we would expect ILI to look like. We'd expect more non-specific terms like the [WHO definition](https://www.who.int/bulletin/volumes/96/2/17-194514/en/) or flu surveillance work.  I haven't had a chance to investigate what PHE and RCGP use as definition for ILI yet in flu surveillance.

**Comment by annaschultze** [comment] 2020-08-25 10:48
@brianmackenna We've ended up not using ILI in the ICS study; we used all non-COVID deaths as the negative control instead. Is it worth moving this issue to the general opencodelist repo? If it's just a matter of adding the documentation then perhaps not worthwhile, but in case there's work to be done actually defining the codes further.

**Comment by CarolineMorton** [comment] 2020-08-25 13:09
True, we should move this to opencodelist repo

Regarding the definition, agree that this does not include all that we would expect. I am pretty sure that it is not being used in any of the studies anymore (@hjforbes ? is this true of yours?) and in that case, we can either scrap it and start again, or expand it to include more symptom based codes?

**Comment by hjforbes** [comment] 2020-08-25 13:22
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by hjforbes** [comment] 2020-08-25 13:22
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by hjforbes** [comment] 2020-08-25 13:22
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by hjforbes** [comment] 2020-08-25 13:24
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by hjforbes** [comment] 2020-08-25 13:24
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by hjforbes** [comment] 2020-08-25 13:24
Correct - this isn't being used anymore.  Can we archive it somewhere in case it comes up in future?

**Comment by CarolineMorton** [comment] 2020-08-25 13:27
i think the issue is that it IS being used in the flu dashboards. 

Do you know if LSHTM have a codelist for influenza like illness that is more broad? maybe Charlotte form the MI stuff?

**Comment by brianmackenna** [comment] 2020-08-25 13:39
Ok so for the moment I think we should
a) change the name of the codelist to something more reflective of what it is - `documented influenza illness`
b) document the methodology on opencodelists so anyone who wants to use can assess

We can revisit and invest more time looking for/develping ILI code lists when we definitely need it.

**Comment by CarolineMorton** [comment] 2020-08-25 13:42
I can document, and i will ask @inglesp to change the name to `documented influenza illness`

**Comment by annaschultze** [comment] 2020-09-01 13:20
Hi @CarolineMorton - just checking whether this has happened so that I can close the issue?

**Comment by CarolineMorton** [comment] 2020-09-01 19:21
Not yet, on leave but will get to this next week. I will take responsibility for closing

**Comment by annaschultze** [comment] 2020-09-16 11:19
@CarolineMorton can I close this issue this week, in time for the paper to appear in publication?

**Closed** 2020-09-21 09:17 UTC

**Comment by CarolineMorton** [comment] 2020-09-21 09:25
This is now done @annaschultze --> https://codelists.opensafely.org/codelist/opensafely/documented-influenza-illness/2020-05-18/

Sorry for the delay.
